name: Run Tests
on:
  pull_request:
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test -- utils
  e2e-tests:
    name: End to End Testing
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "test"
          postgresql user: "test"
          postgresql password: "test"

      - name: Install Dependencies
        run: npm ci

      - name: Run Integration Tests
        env:
          PGDATABASE: test
          PGUSER: test
          PGPASSWORD: test
        run: npm test -- app
