name: Run Tests
on: pull_request
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checout Repo
        uses: actions/checkout@v2

      - name: Use Node.JS
        uses: action/setup-node@v2

      - name: Install Dependencies
        uses: npm i

      - name: Run Unit Tests
        uses: npm t utils
  e2e-tests:
    name: End to End Testing
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checout Repo
        uses: actions/checkout@v2

      - name: Use Node.JS
        uses: action/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "test"
          postgresql user: "test"
          postgresql password: "test"

      - name: Install Dependencies
        uses: npm i

      - name: Run Integration Tests
        uses: PGDATABASE=test PGUSER=test PGPASSWORD=test npm t app
